services:
  dbneo4j:
    image: neo4j:4.4.8-enterprise
    container_name: dbneo4j
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/conf:/conf
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/import
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_default__advertised__address=lenguaje.ups.edu.ec
      - NEO4J_dbms_security_auth__enable=false
      - NEO4J_dbms_connector_http_enable=true
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_bolt_advertised__address=:80
      - NEO4J_dbms_connector_bolt_tls_level=OPTIONAL
      - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
      - NEO4J_dbms_ssl_policy_https_client_auth=NONE
      - NEO4JLABS_PLUGINS='["graph-data-science","apoc"]'
      - NEO4J_AUTH=neo4j/test

  nginx_proxy_demo:
    image: nginx:latest
    container_name: nginx_proxy_demo
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dbneo4j
      - mongo-express
      - mongo

  mongo:
    image: mongo:4.4.6
    container_name: mongo
    restart: always
    volumes:
      - ./mongoDB/data:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "8081:8081"
    depends_on:
      - mongo